### ISSUE TITLE
Crafting Recipes don't function with doLimitedCrafting gamerule set to true

### ISSUE THREAD

**Issue by StarbombC3Y** [TheClassic36/Better-Craftables#3]
### What happened?

Smelting recipes work as intended
![smelting](https://github.com/TheClassic36/Better-Craftables/assets/116328259/f996a5d5-ef8e-4655-a5b7-5313e2fa5548)

Crafting recipes do not function

![Crafting](https://github.com/TheClassic36/Better-Craftables/assets/116328259/516de169-cc59-4cf5-b593-5788b6745d3c)

![Crafting2](https://github.com/TheClassic36/Better-Craftables/assets/116328259/4d1811b1-1474-47f2-8e06-6500ec07c769)
  
![Crafting3](https://github.com/TheClassic36/Better-Craftables/assets/116328259/07e8457a-6230-48e8-8dc7-39aed26682c5)

### Version

v1.5.1

### Minecraft Version

1.20.6

**Comment by StarbombC3Y** [comment]
Update: enabling gamerule doLimtedCrafting False makes it possible to craft the items.

**Comment by TheClassic36** [comment]
Thanks for the report!

Since `doLimitedCrafting` is `true` by default, I'm going to leave the data pack as is for now.

And I'm not sure why anyone would want to play the game with it set to `false` in the first place lol

**Comment by TheClassic36** [comment]
Reopening this - I've re-evaluted & will try to fix it at some point, hopefully after v1.7.0.

**Comment by TheClassic36** [comment]
I believe this has been resolved in [v2.0.0-alpha1](https://github.com/TheClassic36/Better-Craftables/releases/tag/v2.0.0-alpha1). Thanks again for your report!
