### ISSUE TITLE
Wool to 4 string recipe

### ISSUE THREAD

**Issue by babarsc** [TheClassic36/Better-Craftables#4]
### What would you like to see added/changed?

Any color wool placed anywhere in a 2x2 or 3x3 should make 4 string. 

This is the opposite of 4 string to one white wool.

**Comment by TheClassic36** [comment]
Thank you for your suggestion! It will be added in the first beta v1.7.0, after 1.21 releases.

**Comment by TheClassic36** [comment]
Added in [v2.0.0-alpha1](https://github.com/TheClassic36/Better-Craftables/releases/tag/v2.0.0-alpha1) - thanks again for your suggestion!
