### ISSUE TITLE
Alternative recipe for sticky piston

### ISSUE THREAD

**Issue by vgtom4** [TheClassic36/Better-Craftables#6]
### What would you like to see added/changed?

I suggest being able to use a honey bottle to craft a sticky piston.
The recipe is the same as the sticky piston, but with the honey bottle replacing the slime ball.

**Comment by TheClassic36** [comment]
Thanks for your suggestion! It will be added in the next testing release of v2.0.0.

**Comment by TheClassic36** [comment]
Added in [v2.0.0-alpha2](https://github.com/TheClassic36/Better-Craftables/releases/tag/v2.0.0-alpha2) - thanks again!
